import AppWrapper from '@/components/AppWrapper/appWrapper';
import '../globals.css';
import { ThemeProvider } from 'next-themes';

export const metadata = {
  title: "my dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="min-h-screen bg-gray-50 dark:bg-gray-900 dark:text-white transition-colors duration-300">
        <AppWrapper>
          {children}
        </AppWrapper>
      </body>
    </html>
  );
}