import AppWrapper from "@/components/AppWrapper/appWrapper"
import '../globals.css'
import Navbar from "@/components/navbar/navbar"


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
       
        <AppWrapper>
          
        {children}
        </AppWrapper>
        </body>
    </html>
  )
}
