import AppWrapper from "@/components/AppWrapper/appWrapper"
import '../globals.css'



export const metadata = {
  title: 'Dashboard',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AppWrapper>
        {children}

        </AppWrapper>

      </body>
    </html>
  )
}
